#if !defined(FLOW_NAMED_H)
	 #define FLOW_NAMED_H

#include <string>

//!\file named.h
//!
//!\brief Defines the \ref flow::named "named" class.

namespace flow
{

//!\brief Base class for objects that are named.
//!
//! This class is used to name all objects in the flow namespaces.
//! The names of objects are then used to reference them.
//! Names can also help debugging node connections since pipe and pin names are typically generated from the names of the nodes they connect.
class named
{
	std::string d_name;

public:
	//!\brief Constructor the takes a name.
	//!
	//!\param name_r The name of this object.
	named(const std::string& name_r) : d_name(name_r) {}
	
	//!\brief Move constructor.
	named(named&& name_rr) : d_name(std::move(name_rr.d_name)) {}

	//!\brief Copy constructor.
	named(const named& name_r) : d_name(name_r.d_name) {}
	
	virtual ~named() {}

	//!\brief A const reference to this object's name.
	virtual const std::string& name() const { return d_name; }

	//!\brief Sets this object's name to a new name.
	//!
	//!\return This object's former name.
	virtual std::string rename(const std::string& name_r) { std::string old = d_name; d_name = name_r; return old; }
};

}

#endif

/*
	(C) Copyright Thierry Seegers 2010-2012. Distributed under the following license:

	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.
*/
