#if !defined(FLOW_TIMER_H)
	 #define FLOW_TIMER_H

#include <lwsync/critical_resource.hpp>

#include <chrono>
#include <functional>
#include <thread>
#include <vector>

//!\file timer.h
//!
//!\brief Defines the \ref flow::timer base class and the \ref flow::monotonous_timer concrete timer class.

namespace flow
{

//!\brief Base class for an object that notifies listeners at some interval.
class timer
{
	typedef lwsync::critical_resource<std::vector<std::function<void ()> > > listeners_cr_t;
	listeners_cr_t d_listeners_cr;

	lwsync::critical_resource<bool> d_stop_cr;

public:
	timer() : d_stop_cr(false) {}

	virtual ~timer() {}

	//!\brief Returns true if the timer is stopped.
	virtual bool stopped() const
	{
		return *d_stop_cr.const_access();
	}

	//!\brief Stop the timer.
	virtual void stop()
	{
		*d_stop_cr.access() = true;
	}

	//!\brief Adds a listener to this timer.
	//!
	//!\param listener A functor that will be called at interval.
	virtual void listen(const std::function<void ()>& listener)
	{
		d_listeners_cr.access()->push_back(listener);
	}

	//!\brief Returns a reference to listeners.
	virtual listeners_cr_t& listeners()
	{
		return d_listeners_cr;
	}

	//!\brief Execution function to be implemented be concrete timers.
	//!
	//! This function must return as soon as possible after the timer is stopped.
	virtual void operator()() = 0;
};

//!\brief Concrete timer that notifies listeners repeatedly at a set interval of time.
class monotonous_timer : public timer
{
	std::chrono::milliseconds d_interval;

public:
	//!\param interval The time to wait between notifications. Must be a duration typedef from <chrono>.
	template<typename Duration>
	monotonous_timer(const Duration& interval) : d_interval(std::chrono::duration_cast<std::chrono::milliseconds>(interval)) {}

	virtual ~monotonous_timer() {}

	//!\brief Implementation of timer::operator()().
	virtual void operator()()
	{
		while(!stopped())
		{
			{
				auto listeners_a = listeners().access();
				std::for_each(listeners_a->begin(), listeners_a->end(), std::mem_fun_ref(&std::function<void ()>::operator()));
			}
			
			// TODO: wait until time has expired OR timer is stopped.
			std::this_thread::sleep_for(d_interval);
		}
	}
};

}

#endif

/*
	(C) Copyright Thierry Seegers 2010-2012. Distributed under the following license:

	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.
*/
